name: 'DDR Security: Limit the number of simultaneous sessions per user'
type: 'Droptica’s Drupal Recipes'
description: "Limit the number of simultaneous sessions per user"

install:
  - session_limit
  - user

config:
  actions:
    session_limit.settings:
      simpleConfigUpdate:
        session_limit_max: 1
        session_limit_masquerade_ignore: false
        session_limit_behaviour: 0
        session_limit_logged_out_message_severity: warning
        session_limit_roles: []
        session_limit_admin_inclusion: 1
        session_limit_log_events: true

